# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader: false
  body_listener: true
  param_fetcher_listener: true
  format_listener:
    rules:
      - {path: '^/api', priorities: ['json'], fallback_format: json}

  exception:
    enabled: true

  view:
    view_response_listener: 'force'
    formats:
      json: true